project_id = "umfjwvucdqmzufczisca"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[db]
enabled = true
port = 54322
major_version = 15

[functions.create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.pause-subscription]
verify_jwt = true

[functions.resume-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.clean-test-data]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[edge_runtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324