// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umfjwvucdqmzufczisca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZmp3dnVjZHFtenVmY3ppc2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODk1NDQsImV4cCI6MjA2NzY2NTU0NH0._WBuDKw1IfM19ypAMwWw7YoirGUUYZR1GIsTzf2Q6Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});